language: php
dist: trusty
sudo: required
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_install:
  - echo "Start"
install:
  - composer install
before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo cat vendor/codemommy/developphp/file/hhvm.php.ini >> /etc/hhvm/php.ini; fi
script:
  - vendor/bin/phpunit --verbose
after_success:
  - travis_retry vendor/bin/php-coveralls --verbose
after_failure:
  - echo "Error"
after_script:
  - echo "Success"